from flask import request
from pydantic import BaseModel, Field, field_validator
from domain.vo.BaseVO import BaseVO
from decimal import Decimal

class MaterialStorageVO(BaseVO):

    material_id: int | None = Field(default=None)
    material_type_name: str = Field(alias="materialType", default="")
    material_name: str = Field(default="")
    material_model: str = Field(default="")
    material_specification: str = Field(alias="materialSpec", default="")
    color: str = Field(default="")
    material_category: int = Field(default=0)
    purchase_amount: Decimal = Field(alias="estimatedInboundAmount", default=0)
    inbound_amount: Decimal = Field(alias="actualInboundAmount", default=0)
    actual_inbound_unit: str = Field(default="")
    current_amount: Decimal = Field(default=0)
    unit_price: Decimal = Field(default=0)
    average_price: Decimal = Field(default=0)
    total_price: Decimal = Field(default=0)
    supplier_name: str = Field(default="")
    order_id: int | None = Field(default=None) 
    order_rid: str | None = Field(alias="orderRId", default=None)
    order_shoe_id: int | None = Field(alias="orderShoeId", default=None)
    shoe_rid: str | None = Field(alias="shoeRId", default=None)
    material_storage_id: int = Field(default=0)
    shoe_size_columns: list = Field(default=[])

    size_34_purchase_amount: Decimal = Field(alias="estimatedInboundAmount0", default=0)
    size_35_purchase_amount: Decimal = Field(alias="estimatedInboundAmount1", default=0)
    size_36_purchase_amount: Decimal = Field(alias="estimatedInboundAmount2", default=0)
    size_37_purchase_amount: Decimal = Field(alias="estimatedInboundAmount3", default=0)
    size_38_purchase_amount: Decimal = Field(alias="estimatedInboundAmount4", default=0)
    size_39_purchase_amount: Decimal = Field(alias="estimatedInboundAmount5", default=0)
    size_40_purchase_amount: Decimal = Field(alias="estimatedInboundAmount6", default=0)
    size_41_purchase_amount: Decimal = Field(alias="estimatedInboundAmount7", default=0)
    size_42_purchase_amount: Decimal = Field(alias="estimatedInboundAmount8", default=0)
    size_43_purchase_amount: Decimal = Field(alias="estimatedInboundAmount9", default=0)
    size_44_purchase_amount: Decimal = Field(alias="estimatedInboundAmount10", default=0)
    size_45_purchase_amount: Decimal = Field(alias="estimatedInboundAmount11", default=0)
    size_46_purchase_amount: Decimal = Field(alias="estimatedInboundAmount12", default=0)

    size_34_inbound_amount: Decimal = Field(alias="actualInboundAmount0", default=0)
    size_35_inbound_amount: Decimal = Field(alias="actualInboundAmount1", default=0)
    size_36_inbound_amount: Decimal = Field(alias="actualInboundAmount2", default=0)
    size_37_inbound_amount: Decimal = Field(alias="actualInboundAmount3", default=0)
    size_38_inbound_amount: Decimal = Field(alias="actualInboundAmount4", default=0)
    size_39_inbound_amount: Decimal = Field(alias="actualInboundAmount5", default=0)
    size_40_inbound_amount: Decimal = Field(alias="actualInboundAmount6", default=0)
    size_41_inbound_amount: Decimal = Field(alias="actualInboundAmount7", default=0)
    size_42_inbound_amount: Decimal = Field(alias="actualInboundAmount8", default=0)
    size_43_inbound_amount: Decimal = Field(alias="actualInboundAmount9", default=0)
    size_44_inbound_amount: Decimal = Field(alias="actualInboundAmount10", default=0)
    size_45_inbound_amount: Decimal = Field(alias="actualInboundAmount11", default=0)
    size_46_inbound_amount: Decimal = Field(alias="actualInboundAmount12", default=0)

    size_34_current_amount: Decimal = Field(alias="currentAmount0", default=0)
    size_35_current_amount: Decimal = Field(alias="currentAmount1", default=0)
    size_36_current_amount: Decimal = Field(alias="currentAmount2", default=0)
    size_37_current_amount: Decimal = Field(alias="currentAmount3", default=0)
    size_38_current_amount: Decimal = Field(alias="currentAmount4", default=0)
    size_39_current_amount: Decimal = Field(alias="currentAmount5", default=0)
    size_40_current_amount: Decimal = Field(alias="currentAmount6", default=0) 
    size_41_current_amount: Decimal = Field(alias="currentAmount7", default=0)
    size_42_current_amount: Decimal = Field(alias="currentAmount8", default=0)
    size_43_current_amount: Decimal = Field(alias="currentAmount9", default=0)
    size_44_current_amount: Decimal = Field(alias="currentAmount10", default=0)
    size_45_current_amount: Decimal = Field(alias="currentAmount11", default=0)
    size_46_current_amount: Decimal = Field(alias="currentAmount12", default=0)
